var job = 'unemployed';
var grade = 0;

async function addJob(info) {
    var status = 'Wyciągnij';
    var removeButton = '';
    var removeable = 'hidden';

    if (info.stored == 1) {
        removeable = '';
        removeButton = `<div class="job-remove" data-job="" data-grade="">Wymij</div>`;
    }

    if (info.stored == 0) {
        removeable = '';
        removeButton = `<div class="job-remove" data-job="" data-grade="">Schowaj</div>`;
    }
    // 1 wyciagniety
    // 0 schowany
    // 3 odcholownik
    var jobPanel = `
        <div class="job-card">
            <div class="job-name">${info.model}</div>
            <div class="job-grade">${info.plate}</div>
            <div class="job-grade">${info.stored}</div>
            <div style="display: flex; flex-direction: row; flex-wrap: wrap">
                <div class="job-bodyhealth">Karoseria: ${info.vehicle.bodyHealth}</div>
                <div class="job-bodyhealth">Paliwo: ${info.vehicle.bodyHealth}</div>
                <div class="job-bodyhealth">Silnik: ${info.vehicle.bodyHealth}</div>
                <div class="job-bodyhealth">Paliwo: ${info.vehicle.bodyHealth}</div>
            </div>
            <div class="job-status" data-job="" data-grade=""></div>
            ${removeButton}
        </div>
    `
    $("#jobs").append(jobPanel);
}

addJob({
    "model": "Esperanto", "garage": "mayans_garage", "vehicle": {
        "windows": [4, 5],
        "modFender": -1,
        "bodyHealth": 1000,
        "modArchCover": -1,
        "tyres": [],
        "wheelSize": 1.0,
        "modAerials": -1,
        "dirtLevel": 7,
        "modRearBumper": -1,
        "modOrnaments": -1,
        "modSpeakers": -1,
        "modNitrous": -1,
        "modHydraulics": false,
        "modTrimB": -1,
        "modCustomTiresR": false,
        "modSuspension": -1,
        "modFrontWheels": -1,
        "modEngine": -1,
        "neonEnabled": [false, false, false, false],
        "modRoof": -1,
        "modTransmission": -1,
        "modVanityPlate": -1,
        "modSpoilers": -1,
        "modGrille": -1,
        "modXenon": false,
        "pearlescentColor": 0,
        "oilLevel": 5,
        "interiorColor": 144,
        "wheelColor": 0,
        "model": 1338338840,
        "modExhaust": -1,
        "xenonColor": 255,
        "doors": [],
        "modDoorR": -1,
        "color2": 134,
        "neonColor": [255, 0, 255],
        "dashboardColor": 144,
        "modWindows": -1,
        "modRightFender": -1,
        "modSteeringWheel": -1,
        "modLightbar": -1,
        "modTurbo": false,
        "modHydrolic": -1,
        "modDial": -1,
        "modBrakes": -1,
        "tankHealth": 1000,
        "modSmokeEnabled": false,
        "windowTint": -1,
        "modFrontBumper": -1,
        "modRoofLivery": -1,
        "modArmor": -1,
        "modHood": -1,
        "modSubwoofer": -1,
        "color1": 134,
        "modBackWheels": -1,
        "engineHealth": 1000,
        "modShifterLeavers": -1,
        "modHorns": -1,
        "wheelWidth": 1.0,
        "modSeats": -1,
        "modStruts": -1,
        "modLivery": 0,
        "fuelLevel": 65,
        "tyreSmokeColor": [255, 255, 255],
        "modFrame": -1,
        "modEngineBlock": -1,
        "modTank": -1,
        "modDoorSpeaker": -1,
        "extras": [0, 0, 0, 0, 0, 1, null, null, 1, 1, 0],
        "modDashboard": -1,
        "plate": "CPJE8244",
        "modTrunk": -1,
        "modAPlate": -1,
        "modSideSkirt": -1,
        "modAirFilter": -1,
        "modTrimA": -1,
        "modCustomTiresF": false,
        "wheels": 0,
        "plateIndex": 3,
        "modPlateHolder": -1
    }, "type": "car", "body": 1000, "engine": 1000, "plate": "CPJE8244", "fuel": 65, "stored": true
})

vehs = [{
    "model": "Esperanto", "garage": "mayans_garage", "vehicle": {
        "windows": [4, 5],
        "modFender": -1,
        "bodyHealth": 1000,
        "modArchCover": -1,
        "tyres": [],
        "wheelSize": 1.0,
        "modAerials": -1,
        "dirtLevel": 7,
        "modRearBumper": -1,
        "modOrnaments": -1,
        "modSpeakers": -1,
        "modNitrous": -1,
        "modHydraulics": false,
        "modTrimB": -1,
        "modCustomTiresR": false,
        "modSuspension": -1,
        "modFrontWheels": -1,
        "modEngine": -1,
        "neonEnabled": [false, false, false, false],
        "modRoof": -1,
        "modTransmission": -1,
        "modVanityPlate": -1,
        "modSpoilers": -1,
        "modGrille": -1,
        "modXenon": false,
        "pearlescentColor": 0,
        "oilLevel": 5,
        "interiorColor": 144,
        "wheelColor": 0,
        "model": 1338338840,
        "modExhaust": -1,
        "xenonColor": 255,
        "doors": [],
        "modDoorR": -1,
        "color2": 134,
        "neonColor": [255, 0, 255],
        "dashboardColor": 144,
        "modWindows": -1,
        "modRightFender": -1,
        "modSteeringWheel": -1,
        "modLightbar": -1,
        "modTurbo": false,
        "modHydrolic": -1,
        "modDial": -1,
        "modBrakes": -1,
        "tankHealth": 1000,
        "modSmokeEnabled": false,
        "windowTint": -1,
        "modFrontBumper": -1,
        "modRoofLivery": -1,
        "modArmor": -1,
        "modHood": -1,
        "modSubwoofer": -1,
        "color1": 134,
        "modBackWheels": -1,
        "engineHealth": 1000,
        "modShifterLeavers": -1,
        "modHorns": -1,
        "wheelWidth": 1.0,
        "modSeats": -1,
        "modStruts": -1,
        "modLivery": 0,
        "fuelLevel": 65,
        "tyreSmokeColor": [255, 255, 255],
        "modFrame": -1,
        "modEngineBlock": -1,
        "modTank": -1,
        "modDoorSpeaker": -1,
        "extras": [0, 0, 0, 0, 0, 1, null, null, 1, 1, 0],
        "modDashboard": -1,
        "plate": "CPJE8244",
        "modTrunk": -1,
        "modAPlate": -1,
        "modSideSkirt": -1,
        "modAirFilter": -1,
        "modTrimA": -1,
        "modCustomTiresF": false,
        "wheels": 0,
        "plateIndex": 3,
        "modPlateHolder": -1
    }, "type": "car", "body": 1000, "engine": 1000, "plate": "CPJE8244", "fuel": 65, "stored": true
}, {
    "body": 1000.0,
    "engine": 1000.0,
    "plate": "HKRY5163",
    "type": "car",
    "model": "Greenwood",
    "fuel": 65.0,
    "vehicle": {
        "modFender": -1,
        "bodyHealth": 1000.0,
        "modArchCover": -1,
        "modHydrolic": -1,
        "modAerials": -1,
        "dirtLevel": 11.0,
        "modRearBumper": -1,
        "modOrnaments": -1,
        "modSpeakers": -1,
        "engineHealth": 1000.0,
        "modTrimB": -1,
        "modSeats": -1,
        "modSuspension": -1,
        "modFrontWheels": -1,
        "modEngine": -1,
        "tyreSmokeColor": [255, 255, 255],
        "modRoof": -1,
        "modBrakes": -1,
        "modVanityPlate": -1,
        "modSpoilers": -1,
        "modGrille": -1,
        "modXenon": false,
        "pearlescentColor": 0,
        "modTurbo": false,
        "wheelColor": 0,
        "model": -1511720235,
        "doorsBroken": {"0": false, "2": false, "1": false, "4": false, "3": false, "6": false, "5": false},
        "modExhaust": -1,
        "xenonColor": 255,
        "modAPlate": -1,
        "modDoorR": -1,
        "color2": 134,
        "neonColor": [255, 0, 255],
        "modHorns": -1,
        "modRightFender": -1,
        "modSteeringWheel": -1,
        "modLightbar": -1,
        "modDial": -1,
        "modSmokeEnabled": false,
        "windowTint": -1,
        "modFrontBumper": -1,
        "modArmor": -1,
        "modHood": -1,
        "color1": 134,
        "plate": "HKRY5163",
        "modLivery": 0,
        "modTransmission": -1,
        "plateIndex": 0,
        "modStruts": -1,
        "modFrame": -1,
        "fuelLevel": 65.0,
        "modDashboard": -1,
        "modBackWheels": -1,
        "modEngineBlock": -1,
        "modTank": -1,
        "modDoorSpeaker": -1,
        "tyreBurst": {"0": false, "5": false, "4": false, "1": false},
        "extras": {"7": false, "10": false, "5": 1, "6": false, "11": 1},
        "neonEnabled": [false, false, false, false],
        "modTrimA": -1,
        "modSideSkirt": -1,
        "modAirFilter": -1,
        "modShifterLeavers": -1,
        "tankHealth": 1000.0,
        "windowsBroken": {"0": false, "7": false, "2": false, "1": false, "4": true, "3": false, "6": false, "5": true},
        "wheels": 2,
        "modTrunk": -1,
        "modPlateHolder": -1
    },
    "stored": false
}, {
    "body": 1000.0,
    "engine": 1000.0,
    "plate": "QISY4012",
    "type": "car",
    "model": "2013 Chevrolet Caprice",
    "fuel": 65.0,
    "vehicle": {
        "modFender": -1,
        "modShifterLeavers": -1,
        "modArchCover": -1,
        "modHydrolic": -1,
        "modAerials": -1,
        "dirtLevel": 5.0,
        "modRearBumper": -1,
        "modOrnaments": -1,
        "modSpeakers": -1,
        "engineHealth": 1000.0,
        "modTrunk": -1,
        "plate": "QISY4012",
        "modSuspension": -1,
        "modFrontWheels": -1,
        "modEngine": -1,
        "tyreSmokeColor": [255, 255, 255],
        "modRoof": -1,
        "modBrakes": -1,
        "modVanityPlate": -1,
        "modSpoilers": -1,
        "modGrille": -1,
        "modXenon": false,
        "pearlescentColor": 156,
        "modTurbo": false,
        "wheelColor": 156,
        "model": 1568706911,
        "doorsBroken": {"0": false, "2": false, "1": false, "4": false, "3": false, "6": false, "5": false},
        "modExhaust": -1,
        "xenonColor": 255,
        "modAPlate": -1,
        "modDoorR": -1,
        "color2": 134,
        "neonColor": [255, 0, 255],
        "modHorns": -1,
        "modRightFender": -1,
        "modSteeringWheel": -1,
        "modLightbar": -1,
        "modDial": -1,
        "modSmokeEnabled": false,
        "modAirFilter": -1,
        "modSideSkirt": -1,
        "modArmor": -1,
        "modHood": -1,
        "color1": 134,
        "tankHealth": 1000.0,
        "plateIndex": 4,
        "modLivery": 0,
        "bodyHealth": 1000.0,
        "modStruts": -1,
        "modFrame": -1,
        "fuelLevel": 65.0,
        "modDashboard": -1,
        "modBackWheels": -1,
        "modEngineBlock": -1,
        "modTank": -1,
        "modDoorSpeaker": -1,
        "windowTint": -1,
        "tyreBurst": {"0": false, "1": false, "4": false, "5": false},
        "extras": {
            "8": false,
            "7": false,
            "9": false,
            "4": false,
            "3": false,
            "6": false,
            "5": false,
            "2": false,
            "1": 1,
            "10": false,
            "12": 1,
            "11": false
        },
        "neonEnabled": [false, false, false, false],
        "modFrontBumper": -1,
        "modSeats": -1,
        "modTrimB": -1,
        "modTrimA": -1,
        "windowsBroken": {
            "0": false,
            "7": false,
            "2": false,
            "1": false,
            "4": false,
            "3": false,
            "6": false,
            "5": false
        },
        "wheels": 1,
        "modTransmission": -1,
        "modPlateHolder": -1
    },
    "stored": false
}, {
    "model": "2013 Chevrolet Caprice", "garage": "none", "vehicle": {
        "windows": [],
        "modFender": -1,
        "bodyHealth": 1000,
        "modArchCover": -1,
        "tyres": [],
        "wheelSize": 1.0,
        "modAerials": -1,
        "dirtLevel": 6,
        "modRearBumper": -1,
        "modOrnaments": -1,
        "modSpeakers": -1,
        "modNitrous": -1,
        "modHydraulics": false,
        "modTrimB": -1,
        "modCustomTiresR": false,
        "modSuspension": -1,
        "modFrontWheels": -1,
        "modEngine": -1,
        "tankHealth": 1000,
        "modRoof": -1,
        "modTransmission": -1,
        "modVanityPlate": -1,
        "modSpoilers": -1,
        "modGrille": -1,
        "modXenon": false,
        "pearlescentColor": 156,
        "oilLevel": 5,
        "interiorColor": 0,
        "wheelColor": 156,
        "model": 1568706911,
        "modExhaust": -1,
        "xenonColor": 0,
        "doors": [],
        "modDoorR": -1,
        "color2": 134,
        "neonColor": [255, 0, 255],
        "modDashboard": -1,
        "modWindows": -1,
        "modRightFender": -1,
        "modSteeringWheel": -1,
        "modLightbar": -1,
        "modTurbo": false,
        "modHydrolic": -1,
        "modDial": -1,
        "modBackWheels": -1,
        "modBrakes": -1,
        "modSmokeEnabled": true,
        "modAirFilter": -1,
        "modFrontBumper": -1,
        "extras": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        "modArmor": -1,
        "modHood": -1,
        "modSubwoofer": -1,
        "color1": 134,
        "dashboardColor": 0,
        "engineHealth": 1000,
        "modShifterLeavers": -1,
        "modHorns": -1,
        "wheelWidth": 1.0,
        "modSeats": -1,
        "modStruts": -1,
        "modLivery": 0,
        "fuelLevel": 65,
        "tyreSmokeColor": [255, 255, 255],
        "modFrame": -1,
        "modEngineBlock": -1,
        "modTank": -1,
        "modDoorSpeaker": -1,
        "windowTint": 0,
        "neonEnabled": [false, false, false, false],
        "plate": "SFOV3579",
        "modRoofLivery": -1,
        "modSideSkirt": -1,
        "modTrunk": -1,
        "modTrimA": -1,
        "modCustomTiresF": false,
        "modAPlate": -1,
        "wheels": 1,
        "plateIndex": 4,
        "modPlateHolder": -1
    }, "type": "car", "body": 1000, "engine": 1000, "plate": "SFOV3579", "fuel": 65, "stored": false
}, {
    "model": "2013 Chevrolet Caprice", "garage": "none", "vehicle": {
        "windows": [],
        "modFender": -1,
        "bodyHealth": 1000,
        "modArchCover": -1,
        "tyres": [],
        "wheelSize": 1.0,
        "modAerials": -1,
        "dirtLevel": 3,
        "modRearBumper": -1,
        "modOrnaments": -1,
        "modSpeakers": -1,
        "modNitrous": -1,
        "modHydraulics": false,
        "modTrimB": -1,
        "modCustomTiresR": false,
        "modSuspension": -1,
        "modFrontWheels": -1,
        "modEngine": -1,
        "tankHealth": 1000,
        "modRoof": -1,
        "modTransmission": -1,
        "modVanityPlate": -1,
        "modSpoilers": -1,
        "modGrille": -1,
        "modXenon": false,
        "pearlescentColor": 156,
        "oilLevel": 5,
        "interiorColor": 0,
        "wheelColor": 156,
        "model": 1568706911,
        "modExhaust": -1,
        "xenonColor": 255,
        "doors": [],
        "modDoorR": -1,
        "color2": 134,
        "neonColor": [255, 0, 255],
        "modDashboard": -1,
        "modWindows": -1,
        "modRightFender": -1,
        "modSteeringWheel": -1,
        "modLightbar": -1,
        "modTurbo": false,
        "modHydrolic": -1,
        "modDial": -1,
        "modBackWheels": -1,
        "modBrakes": -1,
        "modSmokeEnabled": true,
        "modAirFilter": -1,
        "modFrontBumper": -1,
        "extras": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        "modArmor": -1,
        "modHood": -1,
        "modSubwoofer": -1,
        "color1": 134,
        "dashboardColor": 0,
        "engineHealth": 1000,
        "modShifterLeavers": -1,
        "modHorns": -1,
        "wheelWidth": 1.0,
        "modSeats": -1,
        "modStruts": -1,
        "modLivery": 2,
        "fuelLevel": 65,
        "tyreSmokeColor": [255, 255, 255],
        "modFrame": -1,
        "modEngineBlock": -1,
        "modTank": -1,
        "modDoorSpeaker": -1,
        "windowTint": -1,
        "neonEnabled": [false, false, false, false],
        "plate": "WXFV7818",
        "modRoofLivery": -1,
        "modSideSkirt": -1,
        "modTrunk": -1,
        "modTrimA": -1,
        "modCustomTiresF": false,
        "modAPlate": -1,
        "wheels": 1,
        "plateIndex": 4,
        "modPlateHolder": -1
    }, "type": "car", "body": 1000, "engine": 1000, "plate": "WXFV7818", "fuel": 65, "stored": false
}, {
    "model": "Club", "garage": "none", "vehicle": {
        "windows": [2, 3, 4, 5],
        "modFender": -1,
        "bodyHealth": 957,
        "modArchCover": -1,
        "tyres": [],
        "wheelSize": 0.52000004053115,
        "modAerials": -1,
        "dirtLevel": 5,
        "modRearBumper": -1,
        "modOrnaments": -1,
        "modSpeakers": -1,
        "modNitrous": -1,
        "modHydraulics": false,
        "modTrimB": -1,
        "modCustomTiresR": false,
        "modSuspension": 2,
        "modFrontWheels": 47,
        "modEngine": 3,
        "neonEnabled": [false, false, false, false],
        "modRoof": 3,
        "modTransmission": -1,
        "modVanityPlate": -1,
        "modSpoilers": -1,
        "modGrille": -1,
        "modXenon": false,
        "pearlescentColor": 112,
        "oilLevel": 7,
        "interiorColor": 0,
        "wheelColor": 99,
        "model": -2098954619,
        "modExhaust": 6,
        "xenonColor": 0,
        "doors": [],
        "modDoorR": -1,
        "color2": 0,
        "neonColor": [255, 0, 255],
        "dashboardColor": 0,
        "modWindows": -1,
        "modRightFender": -1,
        "modSteeringWheel": -1,
        "modLightbar": -1,
        "modTurbo": false,
        "modHydrolic": -1,
        "modDial": -1,
        "modBrakes": -1,
        "tankHealth": 996,
        "modSmokeEnabled": true,
        "windowTint": 0,
        "modFrontBumper": -1,
        "modRoofLivery": -1,
        "modArmor": -1,
        "modHood": 3,
        "modSubwoofer": -1,
        "color1": 14,
        "modBackWheels": -1,
        "engineHealth": 736,
        "modShifterLeavers": -1,
        "modHorns": 2,
        "wheelWidth": 0.4199982881546,
        "modSeats": -1,
        "modStruts": -1,
        "modLivery": -1,
        "fuelLevel": 59,
        "tyreSmokeColor": [255, 255, 255],
        "modFrame": -1,
        "modEngineBlock": -1,
        "modTank": -1,
        "modDoorSpeaker": -1,
        "extras": [0],
        "modDashboard": -1,
        "plate": "XPAE0412",
        "modTrunk": -1,
        "modAPlate": -1,
        "modSideSkirt": -1,
        "modAirFilter": -1,
        "modTrimA": -1,
        "modCustomTiresF": false,
        "wheels": 0,
        "plateIndex": 0,
        "modPlateHolder": -1
    }, "type": "car", "body": 957, "engine": 736, "plate": "XPAE0412", "fuel": 59, "stored": false
}, {
    "model": "lib113explo", "garage": "none", "vehicle": {
        "modFender": -1,
        "plateIndex": 4,
        "modArchCover": -1,
        "modHydrolic": -1,
        "modAerials": -1,
        "dirtLevel": 4.0,
        "modRearBumper": -1,
        "modOrnaments": -1,
        "modSpeakers": -1,
        "engineHealth": 1000.0,
        "modTrunk": -1,
        "modSeats": -1,
        "modSuspension": -1,
        "modFrontWheels": -1,
        "modEngine": -1,
        "neonEnabled": [false, false, false, false],
        "modRoof": -1,
        "modBrakes": -1,
        "modVanityPlate": -1,
        "modSpoilers": -1,
        "modGrille": -1,
        "modXenon": false,
        "pearlescentColor": 156,
        "modTurbo": false,
        "wheelColor": 156,
        "model": 1475664754,
        "doorsBroken": {"0": false, "2": false, "1": false, "4": false, "3": false, "6": false, "5": false},
        "modExhaust": -1,
        "xenonColor": 255,
        "modLivery": 3,
        "modDoorR": -1,
        "color2": 134,
        "neonColor": [255, 0, 255],
        "modHorns": -1,
        "modRightFender": -1,
        "modSteeringWheel": -1,
        "modLightbar": -1,
        "modDial": -1,
        "modSmokeEnabled": false,
        "modAirFilter": -1,
        "modFrontBumper": -1,
        "modArmor": -1,
        "modHood": -1,
        "color1": 134,
        "modTransmission": -1,
        "tyreSmokeColor": [255, 255, 255],
        "modShifterLeavers": -1,
        "modAPlate": -1,
        "modStruts": -1,
        "plate": "XRQQ1631",
        "fuelLevel": 80.0,
        "modFrame": -1,
        "modDashboard": -1,
        "modBackWheels": -1,
        "modTank": -1,
        "modDoorSpeaker": -1,
        "tyreBurst": {"0": false, "5": false, "4": false, "1": false},
        "windowTint": -1,
        "extras": {
            "8": false,
            "7": false,
            "9": false,
            "4": 1,
            "3": false,
            "6": false,
            "5": 1,
            "2": false,
            "1": false,
            "10": false,
            "12": false,
            "11": false
        },
        "tankHealth": 1000.0,
        "modTrimA": -1,
        "modTrimB": -1,
        "modSideSkirt": -1,
        "modEngineBlock": -1,
        "windowsBroken": {
            "0": false,
            "7": false,
            "2": false,
            "1": false,
            "4": false,
            "3": false,
            "6": false,
            "5": false
        },
        "wheels": 1,
        "bodyHealth": 1000.0,
        "modPlateHolder": -1
    }, "type": "car", "body": 1000.0, "engine": 1000.0, "plate": "XRQQ1631", "fuel": 80.0, "stored": false
}, {
    "model": "Unknown", "garage": "none", "vehicle": {
        "windows": [4, 5],
        "modFender": -1,
        "plateIndex": 4,
        "modArchCover": -1,
        "tyres": [],
        "wheelSize": 0.0,
        "modAerials": -1,
        "dirtLevel": 10,
        "modRearBumper": -1,
        "modOrnaments": -1,
        "modSpeakers": -1,
        "modNitrous": -1,
        "modHydraulics": false,
        "modTrimB": -1,
        "modCustomTiresR": false,
        "modSuspension": -1,
        "modFrontWheels": -1,
        "modEngine": -1,
        "tankHealth": 1000,
        "modRoof": -1,
        "modTransmission": -1,
        "modVanityPlate": -1,
        "modSpoilers": -1,
        "modGrille": -1,
        "modXenon": false,
        "pearlescentColor": 0,
        "oilLevel": 5,
        "interiorColor": 29,
        "wheelColor": 128,
        "model": -1437054386,
        "modExhaust": -1,
        "xenonColor": 255,
        "doors": [],
        "modDoorR": -1,
        "color2": 16,
        "neonColor": [255, 0, 255],
        "modDashboard": -1,
        "modWindows": -1,
        "modRightFender": -1,
        "modSteeringWheel": -1,
        "modLightbar": -1,
        "modTurbo": false,
        "modHydrolic": -1,
        "modDial": -1,
        "modLivery": -1,
        "modBrakes": -1,
        "modSmokeEnabled": true,
        "modAirFilter": -1,
        "modFrontBumper": -1,
        "dashboardColor": 53,
        "modArmor": -1,
        "modHood": -1,
        "modSubwoofer": -1,
        "color1": 160,
        "bodyHealth": 1000,
        "modCustomTiresF": false,
        "engineHealth": 1000,
        "modBackWheels": -1,
        "modHorns": -1,
        "modShifterLeavers": -1,
        "modStruts": -1,
        "modSeats": -1,
        "fuelLevel": 65,
        "modFrame": -1,
        "extras": [null, 0, 0, null, 0, null, null, null, null, 0],
        "modEngineBlock": -1,
        "modTank": -1,
        "modDoorSpeaker": -1,
        "windowTint": -1,
        "tyreSmokeColor": [255, 255, 255],
        "modRoofLivery": -1,
        "neonEnabled": [false, false, false, false],
        "plate": "ZFQL4157",
        "modTrunk": -1,
        "modAPlate": -1,
        "modSideSkirt": -1,
        "modTrimA": -1,
        "wheels": 0,
        "wheelWidth": 0.0,
        "modPlateHolder": -1
    }, "type": "car", "body": 1000, "engine": 1000, "plate": "ZFQL4157", "fuel": 65, "stored": false
}]

for (let i = 0; i < vehs.length; i++) {
        addJob(vehs[i]);
        console.log(i)
    }

window.addEventListener("load", () => {
    $("body").on("click", ".job-status", function (e) {
        e.preventDefault();

        //$(document).find(".job-status").text('Wybierz');
        //$(this).text('Aktualna');

        $.post('https://valley_garagesapp/changejob', JSON.stringify({
            job: this.dataset.job,
            grade: this.dataset.grade
        }));
    });

    $("body").on("click", ".job-remove", function (e) {
        e.preventDefault();

        $(this).parent().fadeOut();

        $.post('https://valley_garagesapp/removejob', JSON.stringify({
            job: this.dataset.job,
            grade: this.dataset.grade
        }));
    });
});